version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb:/usr/share/mongodb/data
    ports:
      - 27017:27017
    
volumes:
  mongodb:
    driver: local
